# Generic startup file.

#usually equal to number of CPUs you have. run command "grep processor /proc/cpuinfo | wc -l" to find it
worker_processes  auto;
worker_cpu_affinity auto;

error_log  /var/log/nginx/error.log;
pid        /var/run/nginx.pid;

# Keeps the logs free of messages about not being able to bind().
#daemon     off;

events {
    worker_connections  1024;
}

http {
    #rewrite_log on;

    include mime.types;
    default_type       application/octet-stream;
    access_log         /var/log/nginx/access.log;
    sendfile           on;
    #tcp_nopush         on;
    keepalive_timeout  3;
    #tcp_nodelay        on;
    #gzip               on;
    #php max upload limit cannot be larger than this
    client_max_body_size 13m;
    index              index.php index.html index.htm;

    # # Upstream to abstract backend connection(s) for PHP.
    # upstream php {
    #     #this should match value of "listen" directive in php-fpm pool
    #     server unix:/tmp/php-fpm.sock;
    #     # server 127.0.0.1:9000;
    # }

    include sites-enabled/*;

    server {
        listen *:443 ssl;
        listen [::]:443 ssl;

        # indicate locations of SSL key files.
        ssl_certificate inception.crt;
        ssl_certificate_key /run/secrets/ssl-key;
        ssl_protocols TLSv1.2 TLSv1.3;

        server_name mkeerewe.42.fr;

        root /data/www;

        index index.php;

        # Only include one of the files below.
        # include global/wordpress.conf;
        # include global/wordpress-ms-subdir.conf;
        # include global/wordpress-ms-subdomain.conf;

        location / {
            try_files $uri $uri/ /index.php?$args ;
        }

        location ~ \.php$ {
            fastcgi_pass wordpress:9000;
            fastcgi_index index.php;
        }
    }
}