services:
    nginx:
        build:
            context: requirements/nginx
        ports:
            - "443:443"
        volumes:
            - wordpress-files:/var/www/html
        networks:
            - my-network
        env_file: .env
        secrets:
            - ssl-key
        depends_on:
            - wordpress
        restart: unless-stopped

    wordpress:
        build:
            context: requirements/wordpress
        volumes:
            - wordpress-files:/var/www/html
        networks:
            - my-network
        env_file: .env
        depends_on:
            mariadb:
                condition: service_healthy
            redis:
                condition: service_healthy
        restart: unless-stopped

    mariadb:
        build:
            context: requirements/mariadb
        volumes:
            - maria-db:/var/lib/mysql
        networks:
            - my-network
        env_file: .env
        restart: unless-stopped

    redis:
        build:
            context: requirements/redis
        networks:
            - my-network
        env_file: .env
        restart: unless-stopped

    adminer:
        build:
            context: requirements/adminer
        ports:
            - "8080:8080"
        networks:
            - my-network
        depends_on:
            mariadb:
                condition: service_healthy
        restart: unless-stopped

    ftp:
        build:
            context: requirements/ftp
        ports:
            - "21:21"
            - "21000-21010:21000-21010"
        volumes:
            - wordpress-files:/var/www/html
        networks:
            - my-network
        restart: unless-stopped

volumes:
    wordpress-files:
        name: wordpress-files

    maria-db:
        name: maria-db

networks:
    my-network:
        driver: bridge

secrets:
    ssl-key:
        file: ../secrets/inception.key

# docker run --rm --network=my-network -p 3306:3306 --env-file=../../.env -v maria-db:/var/lib/mysql srcs-mariadb
# docker run --rm --network=my-network -p 9000:9000 --env-file=../../.env -v wordpress-files:/workspace/wordpress srcs-wordpress
