[www]
listen = 9000

user = www-data
group = www-data

listen.owner = www-data
listen.group = www-data

clear_env = no

pm = dynamic 
pm.max_children = 75 
pm.start_servers = 10 
pm.min_spare_servers = 5 
pm.max_spare_servers = 20 
pm.process_idle_timeout = 10s
